Blog1/blog/urls.py
"""define urlpatterns of users"""
from django.conf.urls import url

from . import views

app_name = 'blog_urls'

urlpatterns = [
	#hello page
	url(r'^$', views.index, name='index'),
	#mainpage
	url(r'^mainpage/$', views.mainpage, name='mainpage'),
	
	
	#博客部分url
	#blogs
	url(r'^blogs/$', views.blogs, name='blogs'),
	url(r'^blogs/my_blog/$', views.my_blog, name='my_blog'),
	url(r'^blogs/new_blog/$', views.new_blog, name='new_blog'),
	url(r'^blogs/edit_blog/(?P<blog_id>\d+)/$', views.edit_blog, name='edit_blog'),
	url(r'^blogs/delete_blog/(?P<blog_id>\d+)/$', views.delete_blog, name='delete_blog'),


	#微博评论
	url(r'^blogs/comment_blog/(?P<blog_id>\d+)/$', views.comment_blog, name='comment_blog'),
	url(r'^blogs/edit_comment/(?P<comment_id>\d+)/$', views.edit_comment, name='edit_comment'),
	url(r'^blogs/delete_comment/(?P<comment_id>\d+)/$', views.delete_comment, name='delete_comment'),

	
	#好友部分url
	#需要添加查看好友信息以及删除好友操作
	
	#friends
	url(r'^friends/$', views.friends, name='friends'),
	url(r'^friends/add_friends$', views.add_friends, name='add_friends'),
	url(r'^friends/friends_info/(?P<f_username>\w+)/$', views.friends_info, name='friends_info'),
	url(r'^friends/add_friends/add_by_username/(?P<add_username>\w+)/$', views.add_by_username, name='add_by_username'),
	
	
	#消息部分url
	#messages
	url(r'^messages/$', views.messages, name='messages'),
	url(r'^messages/message_op/(?P<checkid>\d+)/(?P<op>\d+)/$', views.message_op, name='message_op'),
	
	
	
	#账户部分url
	#account
	url(r'^account/$', views.account, name='account'),
	#edit photo
	url(r'^account/edit_photo$', views.edit_photo, name='edit_photo'),
	#edit account
	url(r'^account/edit_account$', views.edit_account, name='edit_account'),
	#edit password
	url(r'^account/edit_password$', views.edit_password, name='edit_password'),
]

Blog1/blogpj/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('blog.urls', namespace = 'blog')),
    url(r'^users/', include('users.urls', namespace = 'users')),
]

Blog1/users/urls.py
"""define urlpatterns of users"""
from django.conf.urls import url
from django.contrib.auth.views import login
from . import views

app_name = 'users_urls'

urlpatterns = [
	#login page
	url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
	#logout
	url(r'^logout/$', views.logout_view, name='logout'),
	#register page
	url(r'^register/$', views.register, name='register'),
]

Blog1/users/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=80)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)

class CheckFriends(models.Model):
    user1_ch = models.ForeignKey('UsersUserinfo', models.DO_NOTHING, db_column='user1_ch', related_name='user1_ch')
    user2_ch = models.ForeignKey('UsersUserinfo', models.DO_NOTHING, db_column='user2_ch', related_name='user2_ch')
    checked = models.CharField(max_length=1)
    applicationtime = models.DateTimeField(auto_now_add=True)

    class Meta:
        managed = False
        db_table = 'check_friends'
        unique_together = (('user1_ch', 'user2_ch'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        managed = False
        db_table = 'django_session'


class Friends(models.Model):
    user1 = models.ForeignKey('UsersUserinfo', models.DO_NOTHING, db_column='user1', related_name='user1')
    user2 = models.ForeignKey('UsersUserinfo', models.DO_NOTHING, db_column='user2', related_name='user2')
    addtime = models.DateTimeField(auto_now_add=True)

    class Meta:
        managed = False
        db_table = 'friends'
        unique_together = (('user1', 'user2'),)


class UsersUserinfo(models.Model):
    photo = models.CharField(max_length=100)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING, unique=True)
    nickname = models.CharField(max_length=20, blank=True, null=True)
    sex = models.CharField(max_length=10, blank=True, null=True)
    birthday = models.DateField(blank=True, null=True)
    address = models.CharField(max_length=45, blank=True, null=True)
    motto = models.CharField(max_length=145, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'users_userinfo'

Blog1/users/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect
from django.urls import reverse

from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm
from .models import UsersUserinfo, AuthUser
# Create your views here.

def logout_view(request):
	logout(request)
	return HttpResponseRedirect(reverse('users:login'))

def register(request):
	"""sign in as a new user"""
	if request.method != 'POST':
		form = UserCreationForm()
	else:
		form = UserCreationForm(data=request.POST)
		
		if form.is_valid():
			#save new user
			new_user = form.save()
			tempUser = AuthUser.objects.get(username=new_user.username)
			user_profile = UsersUserinfo(user=tempUser, photo='photos/user1.jpg')
			user_profile.save()
			
			#login
			authenticated_user = authenticate(username=new_user.username,password=request.POST['password1'])
			login(request,authenticated_user)
			
			#goto blog mainpage
			return HttpResponseRedirect(reverse('blog:mainpage'))
	context ={'form': form}
	return render(request, 'users/register.html', context)

Blog1/users/templates/users/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<meta name="Haoran's Blog" content="width=device-width, initial-scale=1"/>
	<script src="{% static 'js/jQuery.js' %}"></script>
	<script src="{% static 'js/materialize.js' %}"></script>
	<link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/materialize.css' %}">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	
	<script src="https://cdn.bootcss.com/particles.js/2.0.0/particles.min.js"></script>
	<link rel="stylesheet" href="{% static 'css/background.css' %}">
	
</head>
<body>
	<div class="fixed-action-btn">
	  <a class="btn-floating btn-large grey lighten-1">
		<i class="large material-icons">menu</i>
	  </a>
	  <ul>
	    <li><a href="{% url 'users:login' %}"  class="btn-floating green tooltipped" data-position="left" data-tooltip="Sign in"><i class="material-icons">playlist_play</i></a></li>
		<li><a href="{% url 'users:register' %}" class="btn-floating blue tooltipped" data-position="left" data-tooltip="Sign up"><i class="material-icons">playlist_add</i></a></li>
		<li><a href="{% url 'blog:index' %}"  class="btn-floating red tooltipped" data-position="left" data-tooltip="Mainpage"><i class="material-icons">reorder</i></a></li>
	  </ul>
	</div>


<div id="particles-js"></div>
	{% block body %}
	{% endblock %}
<script src="{% static 'js/background.js' %}"></script>
<script>
$(document).ready(function(){
    $('.fixed-action-btn').floatingActionButton();
    $('.tooltipped').tooltip();
});
</script>
</body>
</html>

Blog1/users/templates/users/login.html
{% extends "users/base.html" %}
{% load bootstrap3 %}

{% block navbar %}
<a href="{% url 'users:login' %}" class="breadcrumb">
	Sign in
</a>
{% endblock %}


{% block body %}
<style>
div#login-contain{
	height:95vh;
}
</style>	


<div id="login-contain" class="valign-wrapper row login-box ">
	<div class="col card hoverable s10 pull-s1 m6 pull-m3 l4 pull-l4">
		<form method="post" action="{% url 'users:login' %}" class="form">
		{% csrf_token %}
			<div class="card-content">
				<span class="card-title">Sign in</span>
				<div class="row">
					<div class="input-field col s12">
					{% bootstrap_form form %}
					</div>
				</div>
			</div>
			<div class="card-action right-align">
				<button type="reset" id="reset" class="btn-flat grey-text waves-effect" >reset</button>
				<button name = "submit" class="btn waves-effect waves-light" >
					login<i class="material-icons right">send</i>
				</button>
			</div>
			<input type="hidden" name="next" value="{% url 'blog:mainpage' %}" />
		</form>
	</div>
</div>

<script>
$("#reset").on("click", function() {
	$('label').removeClass('active');
});
</script>

{% endblock %}

Blog1/users/templates/users/register.html
{% extends "users/base.html" %}


{% load bootstrap3 %}

{% block body %}
<style>
div#login-contain{
	height:95vh;
}
</style>
<div id="login-contain" class="valign-wrapper row login-box">
	<div class="col card hoverable s10 pull-s1 m6 pull-m3 l4 pull-l4">
		<form method="post" action="{% url 'users:register' %}" class="form">
		{% csrf_token %}
			<div class="card-content">
				<span class="card-title">Sign up</span>
				<div class="row">
					<div class="input-field col s12">
					{% bootstrap_form form %}
					</div>
				</div>
			</div>
			<div class="card-action right-align">
				<button type="reset" id="reset" class="btn-flat grey-text waves-effect" >reset</button>
				<button name = "submit" class="btn waves-effect waves-light" >
					Sign up<i class="material-icons right">send</i>
				</button>
			</div>
			<input type="hidden" name="next" value="{% url 'blog:mainpage' %}" />
		</form>
	</div>
</div>
{% endblock %}