Blog1/blog/urls.py
"""define urlpatterns of users"""
from django.conf.urls import url

from . import views

app_name = 'blog_urls'

urlpatterns = [
	#hello page
	url(r'^$', views.index, name='index'),
	#mainpage
	url(r'^mainpage/$', views.mainpage, name='mainpage'),
	
	
	#博客部分url
	#blogs
	url(r'^blogs/$', views.blogs, name='blogs'),
	url(r'^blogs/my_blog/$', views.my_blog, name='my_blog'),
	url(r'^blogs/new_blog/$', views.new_blog, name='new_blog'),
	url(r'^blogs/edit_blog/(?P<blog_id>\d+)/$', views.edit_blog, name='edit_blog'),
	url(r'^blogs/delete_blog/(?P<blog_id>\d+)/$', views.delete_blog, name='delete_blog'),


	#微博评论
	url(r'^blogs/comment_blog/(?P<blog_id>\d+)/$', views.comment_blog, name='comment_blog'),
	url(r'^blogs/edit_comment/(?P<comment_id>\d+)/$', views.edit_comment, name='edit_comment'),
	url(r'^blogs/delete_comment/(?P<comment_id>\d+)/$', views.delete_comment, name='delete_comment'),

	
	#好友部分url
	#需要添加查看好友信息以及删除好友操作
	
	#friends
	url(r'^friends/$', views.friends, name='friends'),
	url(r'^friends/add_friends$', views.add_friends, name='add_friends'),
	url(r'^friends/friends_info/(?P<f_username>\w+)/$', views.friends_info, name='friends_info'),
	url(r'^friends/add_friends/add_by_username/(?P<add_username>\w+)/$', views.add_by_username, name='add_by_username'),
	
	
	#消息部分url
	#messages
	url(r'^messages/$', views.messages, name='messages'),
	url(r'^messages/message_op/(?P<checkid>\d+)/(?P<op>\d+)/$', views.message_op, name='message_op'),
	
	
	
	#账户部分url
	#account
	url(r'^account/$', views.account, name='account'),
	#edit photo
	url(r'^account/edit_photo$', views.edit_photo, name='edit_photo'),
	#edit account
	url(r'^account/edit_account$', views.edit_account, name='edit_account'),
	#edit password
	url(r'^account/edit_password$', views.edit_password, name='edit_password'),
]

Blog1/blogpj/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('blog.urls', namespace = 'blog')),
    url(r'^users/', include('users.urls', namespace = 'users')),
]

Blog1/blog/models.py
from django.db import models
from users.models import UsersUserinfo
# Create your models here.

class BlogComments(models.Model):
    text = models.CharField(max_length=200)
    creator = models.ForeignKey('users.UsersUserinfo', models.DO_NOTHING)
    blog = models.ForeignKey('BlogsBlog', models.DO_NOTHING)
    createtime = models.DateTimeField(auto_now_add=True)

    class Meta:
        managed = False
        db_table = 'blog_comments'
        verbose_name='Blog Comment'



class BlogPhoto(models.Model):
    photo = models.CharField(max_length=100)
    blog = models.ForeignKey('BlogsBlog', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'blog_photo'


class BlogsBlog(models.Model):
    users_userinfo = models.ForeignKey('users.UsersUserinfo', models.DO_NOTHING)
    text = models.CharField(max_length=200, blank=True, null=True)
    createtime = models.DateTimeField(auto_now_add=True)

    class Meta:
        managed = False
        db_table = 'blogs_blog'
        verbose_name = 'Blog'

Blog1/blog/forms.py
from django import forms
import re

def email_check(email):
	pattern = re.compile(r"\"?([-a-zA-Z0-9.`?{}]+@\w+\.\w+)\"?")
	return re.match(pattern, email)

class UserinfoForm(forms.Form):
	first_name = forms.CharField(label='First Name', max_length=50, required=False)
	last_name = forms.CharField(label='Last Name', max_length=50, required=False)
	nickname = forms.CharField(label='Nickname', max_length=20, required=False)
	sex = forms.ChoiceField(label='gender', choices=(('Male','Male'),('Female','Female'), ('','')), required=False)
	birthday = forms.DateField(label='birthday', required=False)
	email = forms.EmailField(label='Email', required=False)
	address = forms.CharField(label='address', max_length=45, required=False)
	motto = forms.CharField(label='motto', max_length=145, required=False)
	
	sex.widget.attrs.update({'class': 'dropdown-trigger waves-effect'})
	birthday.widget.attrs.update({'class': 'datepicker'})
	# ~ class Meta:
		# ~ model = Loan
		# ~ fields = ['empno', 'isbn', 'loan_date',]
		# ~ widgets = {
			# ~ 'empno': forms.Select(attrs={'class': 'dropdown-trigger btn'}),
			# ~ 'isbn': forms.Select(attrs={'class': 'dropdown-trigger btn'}),
		# ~ }
	
	
	def clean_first_name(self):
		c_first_name = self.cleaned_data.get('first_name')
		if len(c_first_name) >50:
			raise forms.ValidationError("Your first name is too long.")
		return c_first_name

	def clean_last_name(self):
		c_last_name = self.cleaned_data.get('last_name')
		if len(c_last_name) > 50:
			raise forms.ValidationError("Your last name is too long.")
		return c_last_name

	def clean_nickname(self):
		c_nickname = self.cleaned_data.get('nickname')
		if len(c_nickname) > 20:
			raise forms.ValidationError("Your nickname is too long.")
		return c_nickname
		
	def clean_email(self):
		c_email = self.cleaned_data.get('email')
		return c_email

	def clean_address(self):
		c_address = self.cleaned_data.get('address')
		if len(c_address) > 45:
			raise forms.ValidationError("Your address is too long.")
		return c_address
		
	def clean_motto(self):
		c_motto = self.cleaned_data.get('motto')
		if len(c_motto) > 145:
			raise forms.ValidationError("Your motto is too long.")
		return c_motto



class PwdChangeForm(forms.Form):
	old_password = forms.CharField(label='Old password', widget=forms.PasswordInput)
	
	password1 = forms.CharField(label='New Password', widget=forms.PasswordInput)
	password2 = forms.CharField(label='Password Confirmation', widget=forms.PasswordInput)
	
	# Use clean methods to define custom validation rules
	
	def clean_password1(self):
		password1 = self.cleaned_data.get('password1')
		
		if len(password1) < 6:
			raise forms.ValidationError("Your password is too short.")
		elif len(password1) > 20:
			raise forms.ValidationError("Your password is too long.")
		return password1
	
	def clean_password2(self):
		password1 = self.cleaned_data.get('password1')
		password2 = self.cleaned_data.get('password2')
		
		if password1 and password2 and password1 != password2:
			raise forms.ValidationError("Password mismatch. Please enter again.")
		return password2
		
class AddFriendForm(forms.Form):
	text = forms.CharField(label='Search Account', max_length=50)
	choose_type = forms.ChoiceField(label='type', choices=(('Username','Username'),('Nickname','Nickname')))
	choose_type.widget.attrs.update({'class': 'dropdown-trigger waves-effect'})

class SearchFriendForm(forms.Form):
	text = forms.CharField(label='Search Friend', max_length=50, required=False)
	choose_type = forms.ChoiceField(label='type', choices=(('Username','Username'),('Nickname','Nickname')))
	choose_type.widget.attrs.update({'class': 'dropdown-trigger waves-effect'})
	
class BlogForm(forms.Form):
	text = forms.CharField(label='blog', max_length=200, required=False)


class CommentForm(forms.Form):
	text = forms.CharField(label='Comment', max_length=200)

Blog1/blog/views.py
from django.shortcuts import render
from users.models import UsersUserinfo, Friends, CheckFriends
from django.contrib.auth.models import User
from .forms import UserinfoForm, PwdChangeForm, AddFriendForm, SearchFriendForm, BlogForm, CommentForm
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.urls import reverse
from .models import BlogsBlog, BlogPhoto, BlogComments
from django.db import connection
from django.forms.models import model_to_dict

import os
import time, datetime
import json
from operator import itemgetter
from PIL import Image
# Create your views here.

class Mem:
	cur = {}

def get_info_with_id(to_get_id):
	user = User.objects.get(id=to_get_id)
	user_info = UsersUserinfo.objects.get(user_id=to_get_id)
	ret = {'userinfo': user_info, 'user':user }
	return ret


def index(request):
	return render(request, 'blog/index.html')

@login_required
def mainpage(request):
	context = {'account': UsersUserinfo.objects.get(user_id=request.user.id), 'user': request.user}
	return render(request, 'blog/mainpage.html', context)
	

class CJsonEncoder(json.JSONEncoder):
	def default(self, obj):
		if isinstance(obj, datetime.datetime):
			return obj.strftime('%Y-%m-%d %H:%M:%S')
		elif isinstance(obj, datetime.date):
			return obj.strftime('%Y-%m-%d')
		else:
			return json.JSONEncoder.default(self, obj)

def refactoringBlog(obj):
	temp = {}
	#blog info
	temp['id'] = obj[0]
	temp['senduser'] = model_to_dict(UsersUserinfo.objects.get(id=obj[1]))
	#temp['username'] = User.objects.get(id=temp['senduser'].user_id).username
	temp['user'] = model_to_dict(User.objects.get(id=temp['senduser']['user']))
	temp['content'] = obj[2]
	temp['time'] = obj[3]
	photo = []
	tempphotos = BlogPhoto.objects.filter(blog_id=obj[0])
	for p in tempphotos:
		photo.append(model_to_dict(p))
	temp['photo'] = photo
	
	#comments info
	blog = BlogsBlog.objects.get(id=obj[0])
	comments = blog.blogcomments_set.all()
	coms = []
	for comment in comments:
		com = {}
		com['comment_userinfo'] = model_to_dict(UsersUserinfo.objects.get(id=comment.creator_id))
		#com['comment_username'] = User.objects.get(id=com['comment_userinfo'].user_id).username
		com['comment_user'] = model_to_dict(User.objects.get(id=com['comment_userinfo']['user']))
		com['comment'] = model_to_dict(comment)
		com['time'] = comment.createtime
		coms.append(com)
	coms = sorted(coms, key=itemgetter('time'))
	temp['comments'] = coms
	
	return temp

@login_required
def blogs(request):
	user_info = UsersUserinfo.objects.get(user_id=request.user.id)
	user = request.user
	if request.method == "POST":
		mem = Mem()
		blog_list = []
		for i in range(0,10):
			blog = mem.cur[user.username].fetchone()
			if blog:
				blog_list.append(refactoringBlog(blog))
			else:
				break;
		data = json.dumps({'acc':model_to_dict(user_info), 'blog_list': blog_list}, cls=CJsonEncoder)
		return HttpResponse(data)
	Mem.cur[user.username] = connection.cursor()
	mem = Mem()
	mem.cur[user.username].execute(""" select * 
					from blogs_blog 
					where users_userinfo_id = %s 
						  or 
						  users_userinfo_id in 
						  (select X.user1 from friends as X where X.user2 = %s)
						  or 
						  users_userinfo_id in 
						  (select Y.user2 from friends as Y where Y.user1 = %s) 
					order by createtime desc;""",[str(user_info.id),str(user_info.id),str(user_info.id)])
	blog_list = []
	for i in range(0,10):
		blog = mem.cur[user.username].fetchone()
		if blog:
			blog_list.append(refactoringBlog(blog))
		else:
			break;
	
	
	# ~ , 'cursor': json.dumps({'cursor':cur})
	context = {'account': user_info, 'blog_list': json.dumps(blog_list, cls=CJsonEncoder),
			'user': user, 'acc':json.dumps(model_to_dict(user_info), cls=CJsonEncoder)}
	return render(request, 'blog/blogs.html', context)
	
@login_required
def my_blog(request):
	user_info = UsersUserinfo.objects.get(user_id=request.user.id)
	cur = connection.cursor()
	cur.execute(""" select * 
					from blogs_blog 
					where users_userinfo_id = %s 
					order by createtime desc;""",[str(user_info.id)])
	blogs = cur.fetchall()
	blog_list = []
	for blog in blogs:
		blog_list.append(refactoringBlog(blog))

	context = {'account': user_info, 'blogs': blog_list, 'user': request.user, 'acc': user_info}
	return render(request, 'blog/blogs.html', context)

@login_required
def new_blog(request):
	user_info = UsersUserinfo.objects.get(user_id=request.user.id)
	if request.method == 'POST':
		form = BlogForm(request.POST)
		if form.is_valid():
			get_text = form.cleaned_data['text']
			new_blog = BlogsBlog(text=get_text, users_userinfo_id=user_info.id)
			new_blog.save()
			
			photos = request.FILES.getlist('photos')
			if photos:
				cnt = 0
				for photo in photos:
					cnt = cnt + 1
					phototime = str(time.time()).split('.')[0]
					photo_last = str(photo).split('.')[-1]
					photoname = request.user.username + '/photos/' + str(cnt) + '_%s.%s'%(phototime,photo_last)
					img = Image.open(photo)

					#new user
					SavePath = 'blog/static/' + request.user.username + '/photos'
					SavePath = SavePath.strip()
					isExist = os.path.exists(SavePath)
					if not isExist:
						os.makedirs(SavePath)
					
					'''#delete old picture
					old_path = 'users/static/' + (UsersUserinfo.objects.get(user_id=request.user.id)).photo
					if(os.path.exists(old_path)):
						os.remove(old_path)'''
					
					new_photo = BlogPhoto(blog_id=new_blog.id, photo=photoname)
					new_photo.save()
					img.save('blog/static/' + photoname)
	else:
		form = BlogForm()
	
	context = {'account': user_info, 'form': form, 'user': request.user}
	return render(request, 'blog/new_blog.html', context)
	
	
@login_required
def edit_blog(request,blog_id):
	user_info = UsersUserinfo.objects.get(user_id=request.user.id)
	blog_to_edit = BlogsBlog.objects.get(id=blog_id)
	if blog_to_edit.users_userinfo_id != user_info.id:
		raise Http404
	form = BlogForm({'text':blog_to_edit.text})
	if request.method == 'POST':
		form = BlogForm(request.POST)
		if form.is_valid():
			get_text = form.cleaned_data['text']
			BlogsBlog.objects.filter(id=blog_id).update(text=get_text,createtime= datetime.datetime.now())
			'''可以修改为加载原来的照片'''
			#删除原来的照片
			photos_to_delete = BlogPhoto.objects.filter(blog_id=blog_id)
			
			for item in photos_to_delete:
				#delete old picture
				old_path = 'blog/static/' + item.photo
				if(os.path.exists(old_path)):
					os.remove(old_path)
			photos_to_delete.delete()
			
			#删除原来的评论
			BlogComments.objects.filter(blog_id=blog_id).delete()
			
			photos = request.FILES.getlist('photos')
			if photos:
				cnt = 0
				for photo in photos:
					cnt = cnt + 1
					phototime = str(time.time()).split('.')[0]
					photo_last = str(photo).split('.')[-1]
					photoname = request.user.username + '/photos/' + str(cnt) + '_%s.%s'%(phototime,photo_last)
					img = Image.open(photo)

					#new user
					SavePath = 'blog/static/' + request.user.username + '/photos'
					SavePath = SavePath.strip()
					isExist = os.path.exists(SavePath)
					if not isExist:
						os.makedirs(SavePath)
					'''#delete old picture
					old_path = 'users/static/' + (UsersUserinfo.objects.get(user_id=request.user.id)).photo
					if(os.path.exists(old_path)):
						os.remove(old_path)'''
					new_photo = BlogPhoto(blog_id=blog_to_edit.id, photo=photoname)
					new_photo.save()
					img.save('blog/static/' + photoname)
	else:
		photos_to_delete = BlogPhoto.objects.filter(blog_id=blog_id)
			#用户取消更新时，图片不能消失，利用数据库的cascade特性进行删除
			#photos_to_delete.delete()
	context = {'account': user_info, 'form': form, 'user': request.user}
	return render(request, 'blog/new_blog.html', context)


@login_required
def delete_blog(request,blog_id):
	user_info = UsersUserinfo.objects.get(user_id=request.user.id)
	blog = BlogsBlog.objects.get(id=blog_id)
	if blog.users_userinfo_id != user_info.id:
		raise Http404
		
	#删除图片和微博
	photos_to_delete = BlogPhoto.objects.filter(blog_id=blog_id)
	for item in photos_to_delete:
		#delete old picture
		old_path = 'blog/static/' + item.photo
		if(os.path.exists(old_path)):
			os.remove(old_path)
	
	BlogsBlog.objects.filter(id=blog_id).delete()
	return HttpResponseRedirect(reverse('blog:blogs'))



'''
需要在博客页面添加评论按钮
传入博客相关评论以及评论者相关信息
并且显示评论的删除和编辑
删除操作可能需要添加逻辑（博客本人能够删除评论）
'''
@login_required
def comment_blog(request,blog_id):
	user_info = UsersUserinfo.objects.get(user_id=request.user.id)
	if request.method == 'POST':
		form = CommentForm(request.POST)
		if form.is_valid():
			get_text = form.cleaned_data['text']
			new_comment = BlogComments(text=get_text, creator_id=user_info.id, blog_id=blog_id)
			new_comment.save()
			return HttpResponseRedirect(reverse('blog:blogs'))
	else:
		form = CommentForm()
	
	context = {'account': user_info, 'form': form, 'blog_id': blog_id, 'user': request.user}
	return render(request, 'blog/new_comment.html', context)

@login_required
def edit_comment(request,comment_id):
	user_info = UsersUserinfo.objects.get(user_id=request.user.id)
	old_comment = BlogComments.objects.get(id=comment_id)

	if old_comment.creator_id != user_info.id:
		raise Http404
	old_text = old_comment.text
	form = CommentForm({'text': old_text})
	if request.method == 'POST':
		form = CommentForm(request.POST)
		if form.is_valid():
			get_text = form.cleaned_data['text']
			BlogComments.objects.filter(id=comment_id).update(text=get_text,createtime=datetime.datetime.now(),
														blog_id=old_comment.blog_id,creator_id=old_comment.creator_id)
			return HttpResponseRedirect(reverse('blog:blogs'))
	context = {'account': user_info, 'form': form, 'comment_id': comment_id, 'user': request.user}
	return render(request, 'blog/edit_comment.html', context)

@login_required
def delete_comment(request,comment_id):
	user_info = UsersUserinfo.objects.get(user_id=request.user.id)
	comment = BlogComments.objects.get(id=comment_id)

Blog1/blog/templates/blog/account.html
{% extends "blog/base.html" %}
{% block body %}
{% load staticfiles %}

<div class="row">
	<div class="col s12 m5">
		<div class="card hoverable">
			<div class="card-image " style="">
				<a href="{% url 'blog:edit_photo' %}" ><img src="/static/{{account.photo}}"/></a>
			</div>
			<div class="card-content">
				<span>motto:</span>
				<div style="word-wrap:break-word">
					<h6>{{account.motto}}</h6>
				</div>
			</div>
		</div>
	</div>
	<div class="col s12 m7">
		<div class="card hoverable">
			<div class="card-content">
				<table>
					<tbody>
						<tr>	
							<td>nickname</td>
							<td>{{account.nickname}}</td>
						</tr>
						<tr>	
							<td>first_name</td>
							<td>{{account.first_name}}</td>
						</tr>
						<tr>	
							<td>last_name</td>
							<td>{{account.last_name}}</td>
						</tr>
						<tr>	
							<td>gender</td>
							<td>{{account.sex}}</td>
						</tr>
						<tr>	
							<td>birthday</td>
							<td>{{account.birthday}}</td>
						</tr>
						<tr>	
							<td>email</td>
							<td>{{account.email}}</td>
						</tr>
						<tr>	
							<td>address</td>
							<td>{{account.address}}</td>
						</tr>
					</tbody>
				</table>
			</div>
			<div class="card-action">
				<a href="{% url 'blog:edit_account' %}">edit_account</a>
				<a href="{% url 'blog:edit_password' %}">edit password</a>
			</div>
		</div>
	</div>
</div>



{% endblock %}

Blog1/blog/templates/blog/add_by_username.html
{% extends "blog/base.html" %}
{% block body %}
<div class="container" style="margin:3vh">
	<div class="center">
		<h5>{{message}}</h5>
	</div>
	<div class="right">
		<h5><a href="{% url 'blog:add_friends' %}" >Back</h5>
	</div>
</div>
{% endblock %}

Blog1/blog/templates/blog/add_friends.html
{% extends "blog/base.html" %}
{% block body %}

<div id="searchform" >
	<div class="card">
		<form method="post" action="{% url 'blog:add_friends' %}" enctype="multipart/form-data">
			<div class="card-content"  >
			{% csrf_token %}
			{% for field in form %}
			{{ field.label_tag }} {{ field }}{{ field.errors }}
			{% endfor %}
			</div>
			<div class="card-action"\style="center">
			<button name="submit" class="btn  waves-effect waves-teal orange lighten-1">search</button>
			</div>
		</form>
	</div>
</div>

{% if not status %}
	<h5>please input infomation to search user.</h5>
{% elif info_list %}
	{% for m in info_list %}
		{% if info.user.username != user.username %}
<div class="row">
  <div class="col s12 m12">
	<div class="card horizontal hoverable">
	  <div class="card-image">
		<img src="/static/{{m.userinfo.photo}}" alt=""/>
	  </div>
	  <div class="card-stacked">
		<div class="card-content">
		  <table>
			  <tbody>
				  <tr>	
					<td>username</td>
					<td>{{m.user.username}}</td>
				  </tr>
				  <tr>	
					<td>nickname</td>
					<td>{{m.userinfo.nickname}}</td>
				  </tr>
				  <tr>	
					<td>motto</td>
					<td>
						<div style="word-wrap:break-word">
							{{m.userinfo.motto}}
						</div>
					</td>
				  </tr>
			  </tbody>
		  </table>
		</div>
		<div class="card-action">
			<a href="{% url 'blog:add_by_username' m.user.username %}">add</a>
		</div>
	  </div>
	</div>
  </div>
</div>
		{% endif %}
	{% endfor %}
{% else %}
	<h5>No such user.</h5>
{% endif %}

{% endblock %}

Blog1/blog/templates/blog/edit_comment.html
{% extends "blog/base.html" %}
{% block body %}
<div class="container" style="margin:5%">
	<form action="{% url 'blog:edit_comment' comment_id %}" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form }}
		<button id="send_comment" class="btn btn-danger right" type="submit">comment</button>
		<input type="hidden" name="next" value="{% url 'blog:blogs' %}" />
	</form>
</div>
{% endblock %}

Blog1/blog/templates/blog/friends.html
{% extends "blog/base.html" %}

{% block navfix %}
<li><a href="{% url 'blog:add_friends' %}">Add New Friends</a></li>
{% endblock %}

{% block body %}


<style>
#searchform{
	width:100%;
}
</style>
<div id="searchform" >
	<div class="card">
		<form method="post" action="{% url 'blog:friends' %}" enctype="multipart/form-data">
			<div class="card-content"  >
			{% csrf_token %}
			{% for field in form %}
			{{ field.label_tag }} {{ field }}{{ field.errors }}
			{% endfor %}
			</div>
			<div class="card-action"\style="center">
			<button name="submit" class="btn  waves-effect waves-teal orange lighten-1">search</button>
			</div>
		</form>
	</div>
</div>
<h3>
	Friends
</h3>
{% for m in info_list %}
	<!--<button onclick="delete_friend('{{ m.username }}')" >delete</button>-->
<!--
	{% for key,value in m.items %}
		{% if key == 'photo' %}
		<a href="{% url 'blog:friends_info' m.username %}"><img src="/static/{{value}}" alt=""/></a>
		{% else %}
		<li> {{key}}:{{value}} </li>
		{% endif %}
	{% endfor %}
-->

<div class="row">
  <div class="col s12 m12">
    <div class="card horizontal hoverable">
      <div class="card-image">
        <a href="{% url 'blog:friends_info' m.user.username %}"><img src="/static/{{m.userinfo.photo}}" alt=""/></a>
      </div>
      <div class="card-stacked">
        <div class="card-content">
          <table>
			  <tbody>
				  <tr>	
					<td>username</td>
					<td>{{m.user.username}}</td>
				  </tr>
				  <tr>	
					<td>nickname</td>
					<td>{{m.userinfo.nickname}}</td>
				  </tr>
				  <tr>	
					<td>motto</td>
					<td>
						<div style="word-wrap:break-word">
							{{m.userinfo.motto}}
						</div>
					</td>
				  </tr>
			  </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
{% endfor %}









<script>
/*function delete_friend(username){
	var form = new FormData();
	form.append('username',username);
	var xhr = new XMLHttpRequest();
	if (xhr != null)
	{
		xhr.onload=function(){
			location.reload();
		};
		xhr.open('post','', true);
		xhr.send(form);
		
	}
};*/
</script>

{% endblock %}

Blog1/blog/templates/blog/friends_info.html
{% extends "blog/base.html" %}
{% block body %}

<h5>Friend Infomation</h5>



<!--
	{% for key,value in info.items %}
		{% if key == 'photo' %}
		<img src="/static/{{value}}" alt=""/>
		{% elif  key != 'is_friends' %}
		<li> {{key}}:{{value}} </li>
		{% endif %}
	{% endfor %}
-->

<div class="row">
	<div class="col s12 m5">
		<div class="card hoverable">
			<div class="card-image " style="">
				<a href="{% url 'blog:edit_photo' %}" ><img src="/static/{{info.userinfo.photo}}"/></a>
			</div>
			<div class="card-content">
				<span>motto:</span>
				<div style="word-wrap:break-word">
					<h6>{{info.userinfo.motto}}</h6>
				</div>
			</div>
		</div>
	</div>
	<div class="col s12 m7">
		<div class="card hoverable">
			<div class="card-content">
				<table>
					<tbody>
						<tr>	
							<td>nickname</td>
							<td>{{info.userinfo.nickname}}</td>
						</tr>
						<tr>	
							<td>first_name</td>
							<td>{{info.userinfo.first_name}}</td>
						</tr>
						<tr>	
							<td>last_name</td>
							<td>{{info.userinfo.last_name}}</td>
						</tr>
						<tr>	
							<td>gender</td>
							<td>{{info.userinfo.sex}}</td>
						</tr>
						<tr>	
							<td>birthday</td>
							<td>{{info.userinfo.birthday}}</td>
						</tr>
						<tr>	
							<td>email</td>
							<td>{{info.userinfo.email}}</td>
						</tr>
						<tr>	
							<td>address</td>
							<td>{{info.userinfo.address}}</td>
						</tr>
					</tbody>
				</table>
			</div>
			<div class="card-action">
				{% if info.is_friends %}
				<button onclick="delete_friend('{{ info.username }}')" class ="btn waves-effect waves-teal orange lighten-1" >delete</button>
				{% else %}
				<button><a href="{% url 'blog:add_by_username' info.username %}"  class ="btn waves-effect waves-teal orange lighten-1">add</a></button>
				{% endif %}
			</div>
		</div>
	</div>
</div>

<script>
function delete_friend(username){
	var form = new FormData();
	form.append('username',username);
	var xhr = new XMLHttpRequest();
	if (xhr != null)
	{
		xhr.onload=function(){
			window.history.back();
		};
		xhr.open('post','', true);
		xhr.send(form);
	}
};
</script>

{% endblock %}